import { FC, PropsWithChildren } from 'react';
import { NextUIProvider } from '@nextui-org/react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import './globals.scss';

const roboto = Roboto({ weight: ['300', '400', '500', '700', '900'], subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Güney Eroğlu',
  description:
    'Generated by create next app Güney Eroğlu Portfolio Website App Front-End Developer Back-End Developer Software Developer UI software',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang='tr'>
      <body className={roboto.className}>
        <NextUIProvider>
          <header></header>
          <main className='dark text-foreground bg-background'>{children}</main>
          <footer></footer>
        </NextUIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
