import { FC, PropsWithChildren } from 'react';
import { NextUIProvider } from '@nextui-org/react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import Layout from '@components/Layout';

import './globals.scss';

const roboto = Roboto({ weight: ['300', '400', '500', '700', '900'], subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Güney Eroğlu',
  description: `
  Generated by create next app
  Güney Eroğlu Portfolio Website App
  Front-End Developer
  Back-End Developer
  Software Developer 
  UI software development
  JavaScript TypeScript Go Golang C# Node.js
  Next React React Native Angular Fiber Express
  MSSQL PostgreSQL MongoDB
  pq Viper jwt nextui material framer-motion animation reanimated
  `,
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang='en' className='dark text-foreground bg-background'>
      <body className={roboto.className}>
        <NextUIProvider>
          <Layout>{children}</Layout>
        </NextUIProvider>
      </body>
    </html>
  );
};

export default RootLayout;
